# -*- coding: utf-8 -*-

"""OMVT vision-tower self-supervised pretraining entry point.

Runs the four SSL heads (OCR reconstruction, masked patch, orientation,
layout order) on synthetic batches by default. Pass ``--data <jsonl>``
to drive the loop from real images:

* orientation labels are self-generated by random 0/90/180/270 rotation;
* OCR loss is only computed when the row carries ``ocr_labels`` (gracefully
  skipped otherwise, ``w_ocr`` effectively dropped to zero for that step);
* layout-order targets come from the row's ``reading_order`` when present,
  falling back to ``arange`` so existing SSL signal is preserved.
"""

from __future__ import annotations

import argparse
import json
import time
from dataclasses import replace
from pathlib import Path
from typing import Iterator, Sequence

import torch
import torch.nn.functional as F

from Model.config import OMVTConfig
from Model.omvt import (
    LayoutOrderHead,
    MaskedPatchHead,
    OCRReconstructionHead,
    OMVTVisionTower,
    OrientationHead,
    layout_order_loss,
    masked_patch_loss,
    ocr_reconstruction_loss,
    orientation_loss,
)
from Model.training import RankZeroLogger, build_optimizer
from Model.config import TrainingConfig
from Tokenizer.multimodal import PILImageProcessor


def parse_args(argv=None):
    p = argparse.ArgumentParser()
    p.add_argument("--steps", type=int, default=4)
    p.add_argument("--batch-size", type=int, default=2)
    p.add_argument("--image-size", type=int, default=56)
    p.add_argument("--d-vision", type=int, default=64)
    p.add_argument("--compress-to", type=int, default=8)
    p.add_argument("--ocr-vocab", type=int, default=64)
    p.add_argument(
        "--data",
        default="",
        help="JSONL path with rows {'images': [...], 'ocr_labels': [...], 'reading_order': [...]} "
        "(ocr_labels / reading_order optional)",
    )
    p.add_argument("--output", default="outputs/omvt_ssl")
    p.add_argument("--smoke", action="store_true")
    p.add_argument("--lr", type=float, default=3e-4)
    p.add_argument("--seed", type=int, default=42)
    return p.parse_args(argv)


def _omvt_cfg(args) -> OMVTConfig:
    cfg = OMVTConfig(
        image_size=args.image_size,
        d_vision=args.d_vision,
        vertical_patch=(args.image_size // 2, args.image_size // 4),
        horizontal_patch=(args.image_size // 4, args.image_size // 2),
        square_patch=(args.image_size // 4, args.image_size // 4),
        layout_patch=(args.image_size, args.image_size),
        compress_to=args.compress_to,
    )
    return cfg


def _iter_real_jsonl(
    path: str,
    batch_size: int,
    image_processor: PILImageProcessor,
    *,
    seed: int,
) -> Iterator[dict]:
    """Yield batched real-image samples from a JSONL spec.

    Each yielded dict carries ``images`` ``[B,C,H,W]`` plus the optional
    ``ocr_labels`` / ``reading_order`` lists (``None`` when no row in the
    micro-batch supplies them). The iterator wraps around forever so the
    caller controls termination via ``--steps``.
    """

    rng = torch.Generator().manual_seed(seed)
    while True:
        with open(path, "r", encoding="utf-8") as fh:
            buf: list[dict] = []
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                row = json.loads(line)
                if not row.get("images"):
                    continue
                buf.append(row)
                if len(buf) < batch_size:
                    continue
                imgs = [row["images"][0] for row in buf]
                stacked = image_processor(imgs)
                ocr = [row.get("ocr_labels") for row in buf]
                ro = [row.get("reading_order") for row in buf]
                yield {
                    "images": stacked,
                    "ocr_labels": ocr,
                    "reading_order": ro,
                    "rng": rng,
                }
                buf = []


def _rotate_batch(images: torch.Tensor, labels: torch.Tensor) -> torch.Tensor:
    """Apply per-sample 0/90/180/270 rotations matching the orientation labels."""

    out = torch.empty_like(images)
    for i, k in enumerate(labels.tolist()):
        out[i] = torch.rot90(images[i], k=int(k), dims=(1, 2))
    return out


def main(argv=None):
    args = parse_args(argv)
    torch.manual_seed(args.seed)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    cfg = _omvt_cfg(args)
    tower = OMVTVisionTower(cfg).to(device)
    ocr_head = OCRReconstructionHead(cfg.d_vision, args.ocr_vocab).to(device)
    mp_head = MaskedPatchHead(cfg.d_vision, patch_pixels=cfg.square_patch[0] * cfg.square_patch[1] * cfg.in_channels).to(device)
    ori_head = OrientationHead(cfg.d_vision).to(device)
    layout_head = LayoutOrderHead(cfg.d_vision, max_positions=cfg.compress_to).to(device)

    modules = torch.nn.ModuleList([tower, ocr_head, mp_head, ori_head, layout_head])
    train_cfg = TrainingConfig(
        train_data="",
        seq_len=cfg.compress_to,
        micro_batch_size=args.batch_size,
        learning_rate=args.lr,
        weight_decay=0.05,
        max_steps=args.steps,
        warmup_steps=1,
        precision="fp32",
    )
    optimizer = build_optimizer(modules, train_cfg)

    Path(args.output).mkdir(parents=True, exist_ok=True)
    logger = RankZeroLogger(args.output, enable_tensorboard=False)

    t0 = time.time()
    real_iter = None
    if args.data:
        real_iter = _iter_real_jsonl(
            args.data,
            args.batch_size,
            PILImageProcessor(image_size=args.image_size),
            seed=args.seed,
        )

    for step in range(1, args.steps + 1):
        if real_iter is None:
            images = torch.randn(args.batch_size, cfg.in_channels, cfg.image_size, cfg.image_size, device=device)
            ocr_labels_real: list | None = None
            ro_real: list | None = None
        else:
            sample = next(real_iter)
            # Orientation: self-generated label from random rotation —
            # this is the canonical 4-way rotation SSL task.
            ori_labels = torch.randint(0, 4, (args.batch_size,), generator=sample["rng"])
            images = _rotate_batch(sample["images"], ori_labels).to(device)
            ocr_labels_real = sample["ocr_labels"]
            ro_real = sample["reading_order"]

        feats = tower(images)["compressed"]  # [B, compress_to, d_vision]

        ocr_logits = ocr_head(feats)
        if real_iter is None or all(x is None for x in (ocr_labels_real or [])):
            # Synthetic OCR signal (smoke path) or row carries no OCR
            # label: fabricate random targets so the head still trains.
            ocr_labels = torch.randint(0, args.ocr_vocab, (args.batch_size, cfg.compress_to), device=device)
            loss_ocr = ocr_reconstruction_loss(ocr_logits, ocr_labels)
            w_ocr = cfg.w_ocr if real_iter is None else 0.0
        else:
            padded = torch.full((args.batch_size, cfg.compress_to), -100, dtype=torch.long, device=device)
            for i, lab in enumerate(ocr_labels_real):
                if not lab:
                    continue
                lab_t = torch.tensor(lab[: cfg.compress_to], dtype=torch.long, device=device)
                padded[i, : lab_t.numel()] = lab_t
            loss_ocr = ocr_reconstruction_loss(ocr_logits, padded)
            w_ocr = cfg.w_ocr

        masked = mp_head(feats)
        true_patches = torch.randn_like(masked)
        loss_mp = masked_patch_loss(masked, true_patches)

        ori_logits = ori_head(feats)
        if real_iter is None:
            ori_labels = torch.randint(0, 4, (args.batch_size,), device=device)
        else:
            ori_labels = ori_labels.to(device)
        loss_ori = orientation_loss(ori_logits, ori_labels)

        layout_logits = layout_head(feats)
        if real_iter is None or all(x is None for x in (ro_real or [])):
            layout_targets = torch.arange(cfg.compress_to, device=device).unsqueeze(0).expand(args.batch_size, -1)
        else:
            layout_targets = torch.zeros(args.batch_size, cfg.compress_to, dtype=torch.long, device=device)
            base = torch.arange(cfg.compress_to)
            for i, ro in enumerate(ro_real):
                seq = torch.tensor(ro[: cfg.compress_to], dtype=torch.long) if ro else base
                layout_targets[i, : seq.numel()] = seq.to(device)
                if seq.numel() < cfg.compress_to:
                    layout_targets[i, seq.numel():] = base[seq.numel():].to(device)
        loss_layout = layout_order_loss(layout_logits, layout_targets)

        loss = (
            w_ocr * loss_ocr
            + cfg.w_masked_patch * loss_mp
            + cfg.w_orientation * loss_ori
            + cfg.w_layout_order * loss_layout
        )
        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(modules.parameters(), 1.0)
        optimizer.step()

        logger.log(step, {
            "loss": float(loss.detach()),
            "ocr": float(loss_ocr.detach()),
            "mp": float(loss_mp.detach()),
            "ori": float(loss_ori.detach()),
            "layout": float(loss_layout.detach()),
        })

    logger.close()
    dt = time.time() - t0
    print(f"OMVT SSL smoke OK in {dt:.1f}s")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
